KaoLa/urls.py
from django.conf.urls import url

from KaoLa import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index/', views.index, name='index'),
    url(r'^register/', views.register, name='register'),
    url(r'^checkemail/', views.checkemail, name='checkemail'),
    url(r'^signin/', views.signin, name='signin'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^goodsdetail/(\d+)/', views.goodsdetail, name='goodsdetail'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^addcart/', views.addcart, name='addcart'),
    url(r'^chakanstuats/', views.chakanstuats, name='chakanstuats'),
    url(r'^chakanall/', views.chakanall, name='chakanall'),
    url(r'^orderdetail/(.*)/', views.orderdetail, name='orderdetail'),
    url(r'^orderlist/', views.orderlist, name='orderlist'),
    url(r'^generateorder/', views.generateorder, name='generateorder'),
    url(r'^shoporder/', views.shoporder, name='shoporder'),
    url(r'^cartaddgoods/', views.cartaddgoods, name='cartaddgoods'),
    url(r'^cartsugoods/', views.catrsugoods, name='catrsugoods'),
    url(r'^appnotifyurl/', views.appnotifyurl, name='appnotifyurl'),
    url(r'^pay/', views.pay, name='pay'),
    url(r'^shopdel/',views.shopdel,name='shopdel'),
    url(r'^code/',views.code,name='code')
]

kaola/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^kaola/',include('KaoLa.urls',namespace='kaola'))
]

templates/register/register.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>网易用户中心</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" media="screen" title="no title" charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/register.css' %}" media="screen" title="no title" charset="utf-8">
    <link rel="Shortcut Icon" href="favicon(1).ico">
</head>
<body>
<header class="hd-logoBox">
    <div class="hd-wrap">
        <div class="logo"></div>
        <div class="toSign">
            已有账号？去<a href="{% url 'kaola:signin' %}">登录</a>
        </div>
    </div>
</header>
<div class="m-login">
    <h2 class="login-tit">注册账号</h2>
    <div class="login-content">
        {#      <form>#}
        {#        <div class="user-count">#}
        {#          <label for="user-count">账号：</label>#}
        {#          <input type="text" placeholder="6-18位字母数字组合" id="user-count" name="username">#}
        {#          <select class="user-count-mail-type" name="mail-type">#}
        {#            <option value="163"  >@163.com</option>#}
        {#            <option value="126"  >@126.com</option>#}
        {#            <option value="yeah" >@yeah.net</option>#}
        {#          </select>#}
        {#        </div>#}
        {#        <div class="user-password">#}
        {#          <label for="user-pass">密码：</label>#}
        {#          <input type="password" placeholder="6-16位密码，区分大小写" id="user-pass" name="password">#}
        {#        </div>#}
        {#        <div class="user-confirm-pass">#}
        {#          <label for="user-confirm">确认密码：</label>#}
        {#          <input type="password" placeholder="再次输入密码" id="user-confirm">#}
        {#        </div>#}
        {#        <div class="test-code">#}
        {#          <label for="test-code">验证码：</label>#}
        {#          <div class="bg-code">#}
        {#            <div class="move-div">#}
        {#              <img src="img/slider.png" alt="" />#}
        {#            </div>#}
        {#            <span>拖动滑块，完成验证</span>#}
        {#          </div>#}
        {#        </div>#}
        {#        <div class="user-phone">#}
        {#          <label for="phone-num">手机号：</label>#}
        {#          <input type="text" placeholder="11位手机号" id="user-phone">#}
        {#        </div>#}
        {#        <div class="switch-internation-num"  style="width:84px;">#}
        {#          <a href="javascript:">切换到国际手机</a>#}
        {#        </div>#}
        {#        <div class="phone-help">#}
        {#          <span>忘记密码时，可通过手机快速找回密码</span>#}
        {#        </div>#}
        {#        <div class="msg-test-code">#}
        {#          <label for="msg-code">短信验证码：</label>#}
        {#          <input type="text" placeholder="输入短信验证码">#}
        {#          <button type="button" id="btnGetMsgCode">获取验证码</button>#}
        {#        </div>#}
        {#        <div class="btn-login">#}
        {#          <button type="button" id="btnLogin">注&nbsp;&nbsp;册</button>#}
        {#        </div>#}
        {#        <div class="login-info">#}
        {#          用户注册即代表同意#}
        {#          <a href="#">《服务条款》</a>#}
        {#          和#}
        {#          <a href="#">《网络游戏用户隐私保护和个人信息利用政策》</a>#}
        {#        </div>#}
        {#      </form>#}
        <div class="user-count">
            <form id="register" action="{% url 'kaola:register' %}" method="post">
                {% csrf_token %}
                <div class="form-group has-feedback" id="email">
                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1">邮箱</span>
                        <input type="text" class="form-control" placeholder="邮箱" name="email">
                    </div>

                    <span class="glyphicon form-control-feedback   " aria-hidden="true"></span>
                </div>
                <p style="color: red;" id="err"></p>
                <div class="form-group has-feedback" id="password">
                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1">密码</span>
                        <input type="password" class="form-control" placeholder="密码" name="passwrod">
                    </div>

                    <span class="glyphicon form-control-feedback    " aria-hidden="true"></span>
                </div>
                <div class="form-group has-feedback" id="name">
                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1">姓名</span>
                        <input type="text" class="form-control" placeholder="名字(3~10位)" name="name">
                    </div>
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                </div>

                <div class="form-group has-feedback" id="phone">
                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1">手机号</span>
                        <input type="text" class="form-control" placeholder="手机号" name="phone" maxlength="11">
                    </div>
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                </div>
                 <div class="form-group has-feedback" id="code">
                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1">验证码</span>
                        <input type="text" class="form-control" placeholder="验证码"  maxlength="11"  id="inputCode" >
                    </div>
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                </div>
                <div id="checkCode"  class="code" ></div>
                <div id="subButton" class="btn btn-success">注册</div>
            </form>
        </div>
    </div>
</div>
<footer class="ft-aboutNe">
    <ul>
        <li>About NetEase</li>
        -
        <li>公司简介</li>
        -
        <li>联系方式</li>
        -
        <li>OAuth2.0认证</li>
        -
        <li>招聘信息</li>
        -
        <li>客户服务</li>
        -
        <li>相关法律</li>
        -
        <li>网络营销</li>
    </ul>
    <span>网易公司版权所有 &copy;1997-2016</span>
</footer>

<script src="{% static 'js/vendor/jquery-3.1.0.min.js' %}" charset="utf-8"></script>
<script src="{% static 'js/vendor/jquery.cookie.js' %}" charset="utf-8"></script>
<script src="{% static 'js/register.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script>   window.onload=function(){
     createCode(4);
function createCode(length) {
        var code = "";
        var codeLength = parseInt(length); //验证码的长度
        var checkCode = document.getElementById("checkCode");
        ////所有候选组成验证码的字符，当然也可以用中文的
        var codeChars = new Array(0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
        'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z',
        'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z');
        //循环组成验证码的字符串
        for (var i = 0; i < codeLength; i++)
        {
            //获取随机验证码下标
            var charNum = Math.floor(Math.random() * 62);
            //组合成指定字符验证码
            code += codeChars[charNum];
        }
        if (checkCode)
        {
            //为验证码区域添加样式名
            checkCode.className = "code";
            //将生成验证码赋值到显示区
            checkCode.innerHTML = code;
        }
    }
    $('#checkCode').click(function () {
        createCode(4);
    })


    }</script>
</body>
</html>