KaoLa/urls.py
from django.conf.urls import url

from KaoLa import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index/', views.index, name='index'),
    url(r'^register/', views.register, name='register'),
    url(r'^checkemail/', views.checkemail, name='checkemail'),
    url(r'^signin/', views.signin, name='signin'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^goodsdetail/(\d+)/', views.goodsdetail, name='goodsdetail'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^addcart/', views.addcart, name='addcart'),
    url(r'^chakanstuats/', views.chakanstuats, name='chakanstuats'),
    url(r'^chakanall/', views.chakanall, name='chakanall'),
    url(r'^orderdetail/(.*)/', views.orderdetail, name='orderdetail'),
    url(r'^orderlist/', views.orderlist, name='orderlist'),
    url(r'^generateorder/', views.generateorder, name='generateorder'),
    url(r'^shoporder/', views.shoporder, name='shoporder'),
    url(r'^cartaddgoods/', views.cartaddgoods, name='cartaddgoods'),
    url(r'^cartsugoods/', views.catrsugoods, name='catrsugoods'),
    url(r'^appnotifyurl/', views.appnotifyurl, name='appnotifyurl'),
    url(r'^pay/', views.pay, name='pay'),
    url(r'^shopdel/',views.shopdel,name='shopdel'),
    url(r'^code/',views.code,name='code')
]

kaola/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^kaola/',include('KaoLa.urls',namespace='kaola'))
]

KaoLa/models.py
from django.db import models


# Create your models here.
class Wheel(models.Model):
    img = models.CharField(max_length=100)


class User(models.Model):
    email = models.CharField(max_length=100)
    passwrod = models.CharField(max_length=100)
    img = models.CharField(max_length=100)
    phone = models.CharField(max_length=30)
    name = models.CharField(max_length=30)


class Goods(models.Model):
    small_src = models.CharField(max_length=100)
    middle_src = models.CharField(max_length=100)
    big_src = models.CharField(max_length=100)
    brand = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    des = models.CharField(max_length=200)
    discount_price = models.CharField(max_length=40)
    orig_price = models.CharField(max_length=40)


class Cart(models.Model):
    user = models.ForeignKey(User)
    goods = models.ForeignKey(Goods)
    isselect = models.BooleanField(default=True)
    number = models.IntegerField()


class Order(models.Model):
    user = models.ForeignKey(User)
    createtime = models.DateTimeField(auto_now_add=True)
    updatetime = models.DateTimeField(auto_now=True)
    status = models.IntegerField(default=0)
    identifier = models.CharField(max_length=256)


class OrderGoods(models.Model):
    order = models.ForeignKey(Order)
    goods = models.ForeignKey(Goods)
    number = models.IntegerField()

templates/order/orderdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>订单详情页面</title>
</head>
<body>
<div id="orderdetail"style="width: 100%;height: 400px">
    <p>{{ order.identifier }}</p>
    <ul style="list-style: none">
        {% for ordergoods in order.ordergoods_set.all %}
            <li>
                <span>{{ ordergoods.goods.name}}</span>
            <i>X{{ ordergoods.number }}</i>
            </li>

        {% endfor %}
    </ul>
  <button  id="btu" style="width: 100px;height: 50px" orderid="{{ order.id }}">支付</button>
</div>
<script src="/static/js/vendor/jquery-3.1.0.min.js" charset="utf-8"></script>
<script src="/static/js/vendor/jquery.cookie.js" charset="utf-8"></script>
<script src="/static/js/order.js"></script>
</body>
</html>

templates/order/orderlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>订单列表</title>
</head>
<body>

        {% for order in orders %}
            <p class="bg-info">
                <a href="{% url 'kaola:orderdetail' order.identifier %}">
                    订单号: {{ order.identifier }} --
                    {% if order.status == 0 %}
                        未付款
                    {% elif order.status == 1 %}
                        待发货
                    {% elif order.status == 2 %}
                        待收货
                    {% elif order.status == 3 %}
                        待评价
                    {% elif order.status == 4 %}
                        已评价
                    {% endif %}
                </a>
            </p>
            <br>
        {% endfor %}
    </div>

</body>
</html>